window:
  decorations: none

scrolling:
  history: 99999
  multiplier: 3

font:
  normal:
    family: &font-family Victor Mono
    style: Regular
  bold:
    family: *font-family
    style: Bold
  italic:
    family: *font-family
    style: Italic
  bold_italic:
    family: *font-family
    style: Bold Italic
  size: 15.0
  use_thin_strokes: true

draw_bold_text_with_bright_colors: false

# Colors (Tender)
colors:
  # Default colors
  primary:
    background: '0x282828'
    foreground: '0xeeeeee'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xf43753'
    green:   '0xc9d05c'
    yellow:  '0xffc24b'
    blue:    '0xb3deef'
    magenta: '0xd3b987'
    cyan:    '0x73cef4'
    white:   '0xeeeeee'

  # Bright colors
  bright:
    black:   '0x4c4c4c'
    red:     '0xf43753'
    green:   '0xc9d05c'
    yellow:  '0xffc24b'
    blue:    '0xb3deef'
    magenta: '0xd3b987'
    cyan:    '0x73cef4'
    white:   '0xfeffff'

background_opacity: 0.95

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

cursor:
  style: Block

live_config_reload: true

mouse:
  hide_when_typing: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: Equals,    mods: Command,          action: ResetFontSize           }
  - { key: Plus,      mods: Command,          action: IncreaseFontSize        }
  - { key: Minus,     mods: Command,          action: DecreaseFontSize        }
  - { key: K,         mods: Command,          action: ClearHistory            }
  - { key: K,         mods: Command,          chars: "\x0c"                   }
  - { key: V,         mods: Command,          action: Paste                   }
  - { key: C,         mods: Command,          action: Copy                    }
  - { key: H,         mods: Command,          action: Hide                    }
  - { key: M,         mods: Command,          action: Minimize                }
  - { key: N,         mods: Command,          action: SpawnNewInstance        }
  - { key: Q,         mods: Command,          action: Quit                    }
  - { key: F,         mods: Command|Control,  action: ToggleFullscreen        }
  - { key: Return,    mods: Command,          action: ToggleSimpleFullscreen  }
  - { key: Comma,     mods: Command,          command:
      {program: "open", args: ["~/.config/alacritty/alacritty.yml"]}          }

  # Tmux Shortcuts
  - { key: R,         mods: Command,          chars: "\x00,"                  } # Rename Window
  - { key: T,         mods: Command,          chars: "\x00c"                  } # New Window
  - { key: W,         mods: Command,          chars: "\x00&"                  } # Close Window
