shell = "zsh"
apply = ['PATH', 'source']

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

# Completions
# -----

[plugins.rust-zsh-completions]
github = "ryutok/rust-zsh-completions"

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

# Sourced
# -------

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.pure]
github = 'sindresorhus/pure'
use = ["{async,pure}.zsh"]

[plugins.zsh-history-substring-search]
github = 'zsh-users/zsh-history-substring-search'

[plugins.fzf-tab]
github = 'Aloxaf/fzf-tab'
use = ["*.plugin.zsh"]

# Deferred
# -------

[plugins.config]
local = "~/.zsh/plugins"
use = ["*.plugin.zsh"]

[plugins.zsh-mkc]
github = 'caarlos0/zsh-mkc'
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.alias-tips]
github = 'djui/alias-tips'
apply = ['defer']

[plugins.z-lua]
github = "skywind3000/z.lua"
apply = ["defer"]

[plugins.fzf-git]
github = 'hschne/fzf-git'
apply = ['defer']

[plugins.rbenv]
gist = 'nanoxd/d85577bde47b87323656235c47625f11'
apply = ['defer']

[plugins.tsm]
github = 'RobertAudi/tsm'
apply = ['defer']
