# Global matches, if a plugin doesn't provide a `use` field then the first one
# of the following that matches more than zero files will be used.
match = [
  '{{ name }}.zsh',
  '*.zsh',
  '*.sh',
]

# Global templates to apply by default, if a plugin doesn't provide an `apply`
# field then these will be used.
apply = ['PATH', 'source']

# Custom user defined templates, the `each` field means that these will be
# applied for all matched files.
[templates]
completion = { value = 'ln -sf "{{ filename }}" "{{ root }}/completions/_{{ name }}"', each = true }
function = { value = 'ln -sf "{{ filename }}" "{{ root }}/functions/{{ name }}"', each = true }
prompt = { value = 'ln -sf "{{ filename }}" "{{ root }}/functions/prompt_{{ name }}_setup"', each = true }

[plugins.async]
github = 'mafredri/zsh-async'
apply = ['function']

[plugins.pure]
github = 'sindresorhus/pure'
apply = ['prompt']

[plugins.zsh-history-substring-search]
github = 'zsh-users/zsh-history-substring-search'
apply = ['function']

[plugins.zsh-mkc]
github = 'caarlos0/zsh-mkc'
apply = ['function']

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['completion']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['function']

[plugins.alias-tips]
github = 'djui/alias-tips'
apply = ['function']

[plugins.fzf-git]
github = 'hschne/fzf-git'
apply = ['function']

[plugins.rbenv]
gist = 'nanoxd/d85577bde47b87323656235c47625f11'
apply = ['function']

[plugins.tsm]
github = 'RobertAudi/tsm'
apply = ['function']

[plugins.rake-completion]
github = 'unixorn/rake-completion.zshplugin'
apply = ['completion']
